server:
  port: 8443
  servlet:
    context-path: /
    
  ssl:
    enabled: true
    key-store: src/main/resources/bootsecurity.p12
    key-store-password: bootsecurity
    keyStoreType: PKCS12
    keyAlias: bootsecurity

# 5.7 com.mysql.jdbc.Driver
# 5.7 jdbc:mysql://localhost:3306/cos   
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cos?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cos
    password: bitc5600
    
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    user:
      name: cos
      password: bitc5600